// Code generated by pioasm; DO NOT EDIT.

//go:build rp
package dcc
import (
	pio "github.com/tinygo-org/pio/rp2-pio"
)
// dcc

const dccWrapTarget = 0
const dccWrap = 6

var dccInstructions = []uint16{
		//     .wrap_target
		0x00c0, //  0: jmp    pin, 0                     
		0x00c3, //  1: jmp    pin, 3                     
		0x0041, //  2: jmp    x--, 1                     
		0xa0c9, //  3: mov    isr, !x                    
		0x8000, //  4: push   noblock                    
		0xe020, //  5: set    x, 0                       
		0x0040, //  6: jmp    x--, 0                     
		//     .wrap
}
const dccOrigin = -1
func dccProgramDefaultConfig(offset uint8) pio.StateMachineConfig {
	cfg := pio.DefaultStateMachineConfig()
	cfg.SetWrap(offset+dccWrapTarget, offset+dccWrap)
	return cfg;
}

