on:
  push:
    branches:
      - main
    paths:
      - '**.kicad_pcb'

name: KiCad Export

jobs:
  get-changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get changed PCB files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.kicad_pcb
          matrix: true

    outputs:
      any-changed: ${{ steps.changed-files.outputs.any_changed }}
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

  export-images:
    if: ${{ fromJson(needs.get-changed-files.outputs.any-changed) }}
    needs: get-changed-files

    name: Render PCB
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kicad/kicad:9.0
      options: --user root

    strategy:
      matrix:
        files: ${{ fromJSON(needs.get-changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Render PCB images
        shell: bash
        run: |
          # Get the directory of the PCB file
          KICAD_DIR="$(dirname "${{ matrix.files }}")"
          echo "kicad-dir=$KICAD_DIR" >> "$GITHUB_OUTPUT"

          # Get the name of the hardware module
          MODULE_NAME="$(basename $KICAD_DIR)"
          echo "module-name=$MODULE_NAME" >> "$GITHUB_OUTPUT"

          # Render the images
          bash hardware/images.sh $MODULE_NAME

      - name: Store exported images
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-paths.outputs.module-name }}
          path: "images/${{ steps.get-paths.outputs.module-name }}-*.png"
          overwrite: true

  push-changes:
    needs: export-images

    name: Push Changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: images/

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: images/
          default_author: github_actor
          message: "chore: update board images"
